export { default as kuanyshAvatar } from './kuanyshAvatar.png'
export { default as DiasAvatar } from './DiasAvatar.png'
export { default as ArstanAvatar } from './ArstanAvatar.png'
export { default as IslamAvatar } from './IslamAvatar.png'
export { default as AibarAvatar } from './AibarAvatar.png'